import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'
import SourceAccount from '#models/source_account'
import SourceItem from '#models/source_item'
import BusinessIdea from '#models/business_idea'
import StructuredPlan from '#models/structured_plan'
import LaunchPack from '#models/launch_pack'
import BusinessValidation from '#models/business_validation'
import User from '#models/user'

export default class extends BaseSeeder {
  async run() {
    const admin = await User.findByOrFail('email', 'admin@rize.app')
    const member = await User.findByOrFail('email', 'member@rize.app')

    const account = await SourceAccount.updateOrCreate(
      { name: 'Chaine Idees Business' },
      {
        platform: 'youtube',
        name: 'Chaine Idees Business',
        handle: '@ideesbusiness',
        sourceUrl: 'https://youtube.com/@ideesbusiness',
        isActive: true,
      }
    )

    const sourceItems = await SourceItem.updateOrCreateMany('sourceUrl', [
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Lancer un Micro-SaaS avec l\'IA en 2024',
        sourceUrl: 'https://youtube.com/watch?v=demo1',
        rawText: 'Construisez un micro-SaaS qui utilise l\'IA pour automatiser les taches repetitives des petites entreprises. Concentrez-vous sur une niche specifique comme le traitement de factures pour les freelances. Utilisez l\'API OpenAI, facturez 29€/mois, lancez en 30 jours avec des outils no-code.',
        rawMetadata: { views: 150000, likes: 8500 },
        publishedAt: DateTime.fromISO('2024-01-15'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Le modele de newsletter dont personne ne parle',
        sourceUrl: 'https://youtube.com/watch?v=demo2',
        rawText: 'Lancez une newsletter B2B ciblee sur un secteur specifique. Selectionnez les meilleures analyses, atteignez 5K abonnes, puis monetisez avec des emplacements sponsorises a 500-2000€ par edition. Faibles couts, marges elevees, construit votre autorite.',
        rawMetadata: { views: 89000, likes: 4200 },
        publishedAt: DateTime.fromISO('2024-02-10'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Comment creer un service productise',
        sourceUrl: 'https://youtube.com/watch?v=demo3',
        rawText: 'Transformez vos competences freelance en un service a prix fixe. Exemple : "Nous designons votre landing page en 48h pour 997€". Livrable clair, perimetre fixe, tarification premium. Passez a l\'echelle avec une petite equipe et des procedures.',
        rawMetadata: { views: 120000, likes: 6100 },
        publishedAt: DateTime.fromISO('2024-03-05'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Agence d\'automatisation IA - Etape par etape',
        sourceUrl: 'https://youtube.com/watch?v=demo4',
        rawText: 'Lancez une agence d\'automatisation IA pour aider les entreprises a automatiser leurs workflows avec Make, Zapier et ChatGPT. Facturez 2K-10K€ par projet. Cible : petites marques e-commerce noyees dans le travail manuel.',
        rawMetadata: { views: 200000, likes: 12000 },
        publishedAt: DateTime.fromISO('2024-03-20'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Creer un job board de niche',
        sourceUrl: 'https://youtube.com/watch?v=demo5',
        rawText: 'Creez un site d\'emploi pour une niche specifique (ex. emplois IA a distance, tech climat). Monetisez avec des annonces payantes (99-299€/annonce). Peu de maintenance une fois construit. Stack technique simple. Marketing de contenu pour la croissance organique.',
        rawMetadata: { views: 65000, likes: 3100 },
        publishedAt: DateTime.fromISO('2024-04-01'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Lancer un business base sur la communaute',
        sourceUrl: 'https://youtube.com/watch?v=demo6',
        rawText: 'Construisez une communaute payante autour d\'une niche professionnelle. Commencez gratuitement sur Discord, ajoutez un tier premium a 49€/mois avec du contenu exclusif, des AMA et du networking. Focalisez-vous sur la vraie valeur, pas juste le contenu.',
        rawMetadata: { views: 78000, likes: 3800 },
        publishedAt: DateTime.fromISO('2024-04-15'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Empire de templates numeriques',
        sourceUrl: 'https://youtube.com/watch?v=demo7',
        rawText: 'Creez et vendez des templates Notion, Figma ou tableur. Proposez des solutions pour des cas d\'usage specifiques (ex. modele financier pour startup). Vendez sur Gumroad, construisez une marque. Faible effort par vente, marges elevees.',
        rawMetadata: { views: 95000, likes: 5500 },
        publishedAt: DateTime.fromISO('2024-05-01'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Business de generation de leads locaux',
        sourceUrl: 'https://youtube.com/watch?v=demo8',
        rawText: 'Construisez des sites simples pour les entreprises locales (plombiers, dentistes). Positionnez-les sur Google. Vendez les leads aux entreprises locales pour 500-2000€/mois par site. Revenus recurrents, peu de concurrence dans les petites villes.',
        rawMetadata: { views: 110000, likes: 7200 },
        publishedAt: DateTime.fromISO('2024-05-15'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'E-commerce en Print on Demand',
        sourceUrl: 'https://youtube.com/watch?v=demo9',
        rawText: 'Lancez une marque print-on-demand de niche. Concentrez-vous sur une communaute passionnee (ex. races de chiens, hobbies). Designez des produits uniques, vendez via Shopify + Printful. Utilisez les reseaux sociaux et le marketing d\'influence.',
        rawMetadata: { views: 180000, likes: 9800 },
        publishedAt: DateTime.fromISO('2024-06-01'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
      {
        sourceAccountId: account.id,
        platform: 'youtube',
        title: 'Le modele du micro-consulting',
        sourceUrl: 'https://youtube.com/watch?v=demo10',
        rawText: 'Proposez des appels de consulting d\'1 heure a 150-500€ par session dans votre domaine d\'expertise. Utilisez Calendly, Stripe et une landing page simple. Construisez votre autorite par le contenu. Passez a l\'echelle avec des sessions de groupe et des formations.',
        rawMetadata: { views: 55000, likes: 2900 },
        publishedAt: DateTime.fromISO('2024-06-15'),
        ingestedAt: DateTime.now(),
        syncStatus: 'processed',
      },
    ])

    const ideas = await BusinessIdea.updateOrCreateMany('slug', [
      {
        sourceItemId: sourceItems[0].id,
        title: 'Micro-SaaS de traitement de factures par IA',
        slug: 'ai-invoice-processing-micro-saas',
        oneLiner: 'Traitement automatise de factures pour freelances grace a l\'IA',
        summary: 'Un micro-SaaS qui utilise l\'IA pour traiter, categoriser et gerer automatiquement les factures des freelances et petites entreprises.',
        problem: 'Les freelances passent des heures a traiter manuellement les factures, suivre les depenses et preparer les documents fiscaux.',
        solution: 'Un outil alimente par l\'IA qui extrait automatiquement les donnees des factures, categorise les depenses et genere des rapports financiers.',
        audience: 'Freelances et solopreneurs gerant 20+ factures par mois',
        monetizationModel: 'subscription',
        categoryPrimary: 'saas',
        difficultyLevel: 'medium',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 30,
        validationStatus: 'reviewed',
        viabilityScore: 78,
        confidenceScore: 82,
        tags: ['ia', 'saas', 'fintech', 'automatisation', 'freelances'],
        structuredData: { soloFriendly: true, recurringRevenue: true, acquisitionChannels: ['seo', 'contenu', 'product-hunt'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[1].id,
        title: 'Newsletter B2B sectorielle',
        slug: 'b2b-industry-newsletter',
        oneLiner: 'Newsletter B2B avec monetisation par sponsoring',
        summary: 'Une newsletter B2B ciblee qui selectionne les meilleures analyses sectorielles et monetise via des emplacements de sponsoring premium.',
        problem: 'Les professionnels de secteurs de niche manquent d\'une source unique et curatee d\'actualites et d\'analyses pertinentes.',
        solution: 'Une newsletter hebdomadaire avec des analyses triees sur le volet, des decryptages et des conseils pratiques pour un secteur B2B specifique.',
        audience: 'Directeurs marketing et CMO dans le SaaS B2B',
        monetizationModel: 'sponsorship',
        categoryPrimary: 'newsletter-media',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 14,
        validationStatus: 'reviewed',
        viabilityScore: 72,
        confidenceScore: 88,
        tags: ['newsletter', 'media', 'b2b', 'contenu', 'faible-cout'],
        structuredData: { soloFriendly: true, recurringRevenue: true, acquisitionChannels: ['linkedin', 'twitter', 'parrainage'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[2].id,
        title: 'Service de design de landing page en 48h',
        slug: '48h-landing-page-design-service',
        oneLiner: 'Design de landing page a prix fixe livre en 48 heures',
        summary: 'Un service de design productise proposant la creation de landing pages a prix fixe avec livraison en 48 heures.',
        problem: 'Les startups ont besoin de landing pages professionnelles mais les agences sont cheres et lentes.',
        solution: 'Un service a perimetre fixe et prix fixe qui livre une landing page optimisee pour la conversion en 48 heures.',
        audience: 'Startups early-stage et indie hackers lancant de nouveaux produits',
        monetizationModel: 'productized-service',
        categoryPrimary: 'freelance-productized-service',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 7,
        validationStatus: 'reviewed',
        viabilityScore: 85,
        confidenceScore: 90,
        tags: ['design', 'service', 'productise', 'startup', 'landing-page'],
        structuredData: { soloFriendly: true, recurringRevenue: false, acquisitionChannels: ['twitter', 'indie-hackers', 'parrainage'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[3].id,
        title: 'Agence d\'automatisation IA pour e-commerce',
        slug: 'ai-automation-agency-ecommerce',
        oneLiner: 'Aidez les marques e-commerce a automatiser leurs workflows avec l\'IA',
        summary: 'Une agence specialisee dans la creation d\'automatisations alimentees par l\'IA pour les entreprises e-commerce.',
        problem: 'Les petites marques e-commerce perdent 20+ heures par semaine sur des taches repetitives comme le traitement des commandes, le support client et les mises a jour de stock.',
        solution: 'Mise en place d\'automatisations IA cle en main avec Make, Zapier et ChatGPT, adaptees aux workflows e-commerce.',
        audience: 'Marques e-commerce generant 50K-500K€/mois de CA',
        monetizationModel: 'project-based',
        categoryPrimary: 'ai-automation',
        difficultyLevel: 'medium',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 21,
        validationStatus: 'processed',
        viabilityScore: 82,
        confidenceScore: 75,
        tags: ['ia', 'automatisation', 'agence', 'ecommerce', 'no-code'],
        structuredData: { soloFriendly: true, recurringRevenue: false, acquisitionChannels: ['prospection', 'linkedin', 'etudes-de-cas'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[4].id,
        title: 'Job board emplois IA a distance',
        slug: 'remote-ai-jobs-board',
        oneLiner: 'Site d\'emploi de niche pour les postes IA et ML a distance',
        summary: 'Un site d\'emploi specialise exclusivement dans les postes a distance en IA, ML et data science.',
        problem: 'Les professionnels de l\'IA peinent a trouver des postes remote de qualite sur des plateformes dispersees.',
        solution: 'Un job board specialise pour les postes IA/ML a distance avec filtrage qualitatif et alertes.',
        audience: 'Ingenieurs IA/ML et data scientists recherchant du travail a distance',
        monetizationModel: 'paid-listings',
        categoryPrimary: 'recruiting',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 21,
        validationStatus: 'processed',
        viabilityScore: 68,
        confidenceScore: 72,
        tags: ['job-board', 'ia', 'teletravail', 'marketplace', 'niche'],
        structuredData: { soloFriendly: true, recurringRevenue: true, acquisitionChannels: ['seo', 'twitter', 'communautes'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[5].id,
        title: 'Communaute professionnelle DevOps',
        slug: 'devops-professional-community',
        oneLiner: 'Communaute payante premium pour les praticiens DevOps',
        summary: 'Une communaute professionnelle payante pour les ingenieurs DevOps avec du contenu exclusif, des AMA et du networking entre pairs.',
        problem: 'Les ingenieurs DevOps manquent d\'une communaute dediee pour des discussions techniques approfondies et l\'evolution de carriere.',
        solution: 'Une communaute premium Discord/Slack avec des AMA hebdomadaires, des ressources selectionnees et du mentorat entre pairs.',
        audience: 'Ingenieurs DevOps et SRE de niveau intermediaire a senior',
        monetizationModel: 'membership',
        categoryPrimary: 'community',
        difficultyLevel: 'medium',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 30,
        validationStatus: 'processed',
        viabilityScore: 64,
        confidenceScore: 68,
        tags: ['communaute', 'devops', 'abonnement', 'networking'],
        structuredData: { soloFriendly: true, recurringRevenue: true, acquisitionChannels: ['linkedin', 'dev-to', 'twitter'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[6].id,
        title: 'Templates de modeles financiers pour startups',
        slug: 'startup-financial-model-templates',
        oneLiner: 'Templates premium de modelisation financiere pour startups',
        summary: 'Une collection de templates de modeles financiers prets a l\'emploi en Google Sheets et Notion pour differents types de startups.',
        problem: 'Les fondateurs debutants peinent a construire des projections financieres pour la levee de fonds ou la planification.',
        solution: 'Des templates de modeles financiers pre-construits et personnalisables avec tutoriels, concus pour des business models specifiques.',
        audience: 'Fondateurs debutants preparant une levee de fonds ou un bootstrapping',
        monetizationModel: 'digital-product',
        categoryPrimary: 'info-product',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 14,
        validationStatus: 'reviewed',
        viabilityScore: 74,
        confidenceScore: 85,
        tags: ['templates', 'finance', 'startup', 'produit-numerique', 'notion'],
        structuredData: { soloFriendly: true, recurringRevenue: false, acquisitionChannels: ['gumroad', 'twitter', 'product-hunt'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[7].id,
        title: 'Generation de leads locaux pour cabinets dentaires',
        slug: 'local-lead-gen-dental-clinics',
        oneLiner: 'Sites rank-and-rent pour les cabinets dentaires locaux',
        summary: 'Construisez des sites optimises SEO pour les services dentaires dans des villes specifiques et vendez les leads aux cabinets locaux.',
        problem: 'Les cabinets dentaires locaux peinent a generer des leads patients de maniere constante via les canaux en ligne.',
        solution: 'Des sites pre-positionnes dans les resultats de recherche locaux qui generent et vendent des leads patients qualifies.',
        audience: 'Cabinets dentaires dans des villes moyennes sans forte presence en ligne',
        monetizationModel: 'lead-gen-recurring',
        categoryPrimary: 'lead-generation',
        difficultyLevel: 'medium',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 60,
        validationStatus: 'draft',
        viabilityScore: 70,
        confidenceScore: 65,
        tags: ['seo-local', 'generation-leads', 'dentaire', 'recurrent', 'rank-and-rent'],
        structuredData: { soloFriendly: true, recurringRevenue: true, acquisitionChannels: ['seo', 'prospection'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[8].id,
        title: 'Marque Print-on-Demand races de chiens',
        slug: 'dog-breed-pod-brand',
        oneLiner: 'Marque e-commerce POD de niche pour passionnes de races de chiens',
        summary: 'Une marque print-on-demand creant des produits uniques pour les communautes de passionnes de races de chiens specifiques.',
        problem: 'Les passionnes de races de chiens veulent des produits uniques et de qualite qui celebrent leur race specifique.',
        solution: 'Une boutique Shopify avec des designs par race sur des vetements, accessoires et deco via Printful.',
        audience: 'Proprietaires de chiens passionnes participant activement aux communautes de races',
        monetizationModel: 'ecommerce',
        categoryPrimary: 'ecommerce',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'medium',
        estimatedLaunchTimeDays: 21,
        validationStatus: 'draft',
        viabilityScore: 62,
        confidenceScore: 70,
        tags: ['ecommerce', 'pod', 'chiens', 'niche', 'shopify'],
        structuredData: { soloFriendly: true, recurringRevenue: false, acquisitionChannels: ['instagram', 'groupes-facebook', 'tiktok'] },
        createdByUserId: admin.id,
      },
      {
        sourceItemId: sourceItems[9].id,
        title: 'Micro-consulting pour Product Managers',
        slug: 'micro-consulting-product-managers',
        oneLiner: 'Consulting a la demande d\'1 heure pour les PM',
        summary: 'Un service de micro-consulting proposant des sessions strategiques d\'1 heure a la demande pour les product managers.',
        problem: 'Les product managers font face a des decisions complexes mais manquent d\'acces a des mentors experimentes pour des conseils rapides.',
        solution: 'Reservez des appels d\'1 heure avec des PM experimentes pour des defis specifiques comme la priorisation de roadmap ou l\'alignement des parties prenantes.',
        audience: 'Product managers en debut de carriere dans des entreprises SaaS B2B',
        monetizationModel: 'consulting',
        categoryPrimary: 'freelance-productized-service',
        difficultyLevel: 'easy',
        startupBudgetLevel: 'low',
        estimatedLaunchTimeDays: 7,
        validationStatus: 'draft',
        viabilityScore: 66,
        confidenceScore: 80,
        tags: ['consulting', 'product-management', 'mentorat', 'solo'],
        structuredData: { soloFriendly: true, recurringRevenue: false, acquisitionChannels: ['linkedin', 'twitter', 'parrainage'] },
        createdByUserId: admin.id,
      },
    ])

    // Creation de 2 plans structures
    await StructuredPlan.updateOrCreateMany(['businessIdeaId', 'version'], [
      {
        businessIdeaId: ideas[0].id,
        version: 1,
        status: 'completed',
        createdByUserId: admin.id,
        content: {
          marketAngle: 'Se concentrer sur le segment sous-desservi des freelances gerant 20-100 factures mensuelles mais ne pouvant pas justifier un logiciel comptable d\'entreprise.',
          targetPersona: { name: 'Sarah la designeuse freelance', demographics: '28-40 ans, urbaine, freelance a l\'aise avec la tech', painPoints: ['Saisie manuelle de donnees', 'Stress de la periode fiscale', 'Factures perdues'], goals: ['Gagner 5+ heures/semaine', 'Ne jamais rater une deduction fiscale', 'Facturation professionnelle'] },
          offerHypothesis: '29€/mois pour 100 factures max, 49€/mois illimite avec fonctionnalites de preparation fiscale.',
          gtmOutline: { channels: ['Product Hunt', 'Indie Hackers', 'Subreddits freelance'], strategy: 'Lancement sur PH, offrir 50% de reduction a vie pour les 100 premiers utilisateurs, construire des etudes de cas.', timeline: 'Sprint de lancement de 30 jours' },
          mvpScope: { coreFeatures: ['Upload de factures (PDF/photo)', 'Extraction de donnees par IA', 'Categorisation des depenses', 'Rapport mensuel de synthese'], niceToHave: ['Multi-devises', 'Estimation d\'impots', 'Portail client'], outOfScope: ['Comptabilite complete', 'Paie', 'Inventaire'] },
          thirtyDayRoadmap: [{ week: 1, tasks: ['Mise en place du stack technique', 'Construire le flux d\'upload de factures', 'Integrer l\'API OpenAI'] }, { week: 2, tasks: ['Construire le tableau de bord', 'Ajouter la logique de categorisation', 'Tests'] }, { week: 3, tasks: ['Landing page', 'Integration Stripe', 'Systeme d\'invitation beta'] }, { week: 4, tasks: ['Lancement Product Hunt', 'Onboarder les premiers utilisateurs', 'Collecter les retours'] }],
          validationSteps: ['Interviewer 10 freelances sur leurs galeres de facturation', 'Construire une landing page et mesurer les inscriptions', 'Lancer la beta avec 20 utilisateurs', 'Mesurer la retention apres la semaine 2'],
          operationalChecklist: ['Configurer la facturation Stripe', 'Configurer l\'API OpenAI avec limites de debit', 'Mettre en place le monitoring d\'erreurs', 'Creer l\'email de support'],
          risks: ['Les couts de l\'API OpenAI pourraient grignoter les marges a grande echelle', 'Les formats de factures varient enormement, problemes de precision', 'Concurrence avec des outils gratuits comme Wave'],
          assumptions: ['Les freelances traitent assez de factures pour justifier 29€/mois', 'Precision de l\'extraction IA superieure a 90%', 'Les freelances preferent un outil specialise a un logiciel comptable generaliste'],
        },
        markdown: null,
      },
      {
        businessIdeaId: ideas[2].id,
        version: 1,
        status: 'completed',
        createdByUserId: admin.id,
        content: {
          marketAngle: 'Se positionner comme l\'option de landing page la plus rapide et abordable pour les fondateurs bootstrappes qui veulent de la qualite sans les prix d\'agence.',
          targetPersona: { name: 'Alex l\'indie hacker', demographics: '25-35 ans, fondateur technique, bootstrappe un side project', painPoints: ['Pas de competences en design', 'Ne peut pas se permettre 5K€ d\'agence', 'Besoin de livrer vite'], goals: ['Lancer rapidement', 'Avoir un look professionnel', 'Convertir les visiteurs'] },
          offerHypothesis: '997€ prix fixe pour une landing page complete livree en 48 heures. Inclut un tour de revisions.',
          gtmOutline: { channels: ['Twitter/X', 'Indie Hackers', 'Product Hunt'], strategy: 'Partager les resultats avant/apres sur Twitter, offrir une reduction pour les temoignages, construire le portfolio rapidement.', timeline: 'Sprint de lancement de 7 jours' },
          mvpScope: { coreFeatures: ['Formulaire de brief', 'Livraison du design', 'Un tour de revisions', 'Design responsive'], niceToHave: ['Mise en place de tests A/B', 'Integration analytics', 'Option redaction'], outOfScope: ['Design de site complet', 'Maintenance continue', 'Developpement'] },
          thirtyDayRoadmap: [{ week: 1, tasks: ['Creer le site portfolio', 'Designer le formulaire de brief', 'Configurer Stripe'] }, { week: 2, tasks: ['Realiser 3 projets gratuits pour les temoignages', 'Publier les resultats sur Twitter'] }, { week: 3, tasks: ['Lancer l\'offre payante', 'Contacter les communautes indie hacker'] }, { week: 4, tasks: ['Optimiser le processus avec des templates', 'Recruter le premier sous-traitant si besoin'] }],
          validationSteps: ['Realiser 3 projets gratuits pour construire le portfolio', 'Publier les resultats sur Twitter, mesurer l\'engagement', 'Obtenir 5 clients payants dans les 2 premieres semaines', 'Mesurer la satisfaction client et le taux de parrainage'],
          operationalChecklist: ['Creer un espace Notion pour la gestion de projet', 'Configurer Calendly pour les appels de brief', 'Construire la bibliotheque de templates design', 'Creer le workflow de livraison'],
          risks: ['Le delai de 48h peut etre insoutenable en solo', 'Depassement de perimetre par les clients', 'Sensibilite au prix dans le marche cible'],
          assumptions: ['Les fondateurs paieront 997€ pour la rapidite et la qualite', 'Le delai de 48h est tenable avec des templates', 'Twitter est le bon canal d\'acquisition'],
        },
        markdown: null,
      },
    ])

    // Creation de 2 packs de lancement
    await LaunchPack.updateOrCreateMany(['businessIdeaId', 'version'], [
      {
        businessIdeaId: ideas[0].id,
        version: 1,
        status: 'completed',
        createdByUserId: admin.id,
        brandNames: ['InvoiceAI', 'FactureBot', 'FreelanceCompta', 'AutoFacture', 'InvoFlow', 'FactureSense', 'Receiptly', 'FactureGenius', 'QuickBill IA', 'ComptaLite'],
        domainSuggestions: ['invoiceai.fr', 'facturebot.io', 'invoflow.app', 'facturesense.fr', 'receiptly.io', 'facturegenius.app', 'quickbillai.com', 'comptalite.fr', 'freelancecompta.com', 'autofacture.io'],
        websiteOutline: { sections: [{ title: 'Accroche', content: 'Arretez de perdre des heures sur vos factures. Laissez l\'IA s\'en charger.' }, { title: 'Probleme', content: 'Les freelances perdent 5+ heures/semaine a gerer leurs factures' }, { title: 'Solution', content: 'Uploadez vos factures, obtenez une categorisation et des rapports instantanes' }, { title: 'Tarifs', content: 'Tarification simple a partir de 29€/mois' }] },
        marketingPlan: { channels: ['Product Hunt', 'Twitter', 'Reddit'], contentCalendar: 'Conseils hebdomadaires sur la gestion financiere des freelances', partnerships: 'Integration avec les outils de facturation populaires' },
        launchChecklist: ['Construire le MVP avec le traitement de factures de base', 'Creer la landing page', 'Configurer la facturation Stripe', 'Lancer sur Product Hunt', 'Publier sur Indie Hackers', 'Ecrire 3 articles de blog sur la finance freelance'],
        contentAngles: ['Comment j\'ai automatise ma facturation avec l\'IA', '5 erreurs de facturation que font les freelances', 'Le vrai cout de la comptabilite manuelle'],
        offerDesign: { mainOffer: '29€/mois pour 100 factures', upsell: '49€/mois illimite', annualDiscount: '2 mois offerts sur l\'abonnement annuel' },
        assumptions: ['Les freelances traitent assez de factures pour justifier le cout', 'La precision de l\'IA est suffisante pour les donnees financieres', 'Le lancement Product Hunt genere 500+ inscriptions'],
        markdown: null,
      },
      {
        businessIdeaId: ideas[2].id,
        version: 1,
        status: 'completed',
        createdByUserId: admin.id,
        brandNames: ['PageCraft', 'ShipLanding', 'LancementPro', 'PixelShip', '48Pages', 'QuickLanding', 'FounderPages', 'DesignSprint', 'PageSprint', 'ConvertCraft'],
        domainSuggestions: ['pagecraft.fr', 'shiplanding.io', 'lancementpro.design', 'pixelship.fr', '48pages.com', 'quicklanding.io', 'founderpages.com', 'pagesprint.fr', 'convertcraft.design', 'designsprint.fr'],
        websiteOutline: { sections: [{ title: 'Accroche', content: 'Votre landing page, designee en 48 heures. 997€ prix fixe.' }, { title: 'Portfolio', content: 'Avant/apres : les projets realises' }, { title: 'Processus', content: '3 etapes simples : Brief, Design, Livraison' }, { title: 'Temoignages', content: 'Ce que disent les fondateurs de notre service' }] },
        marketingPlan: { channels: ['Twitter/X', 'Indie Hackers', 'LinkedIn'], contentCalendar: 'Partager des astuces design et des resultats avant/apres chaque semaine', partnerships: 'Partenariat avec les constructeurs no-code' },
        launchChecklist: ['Construire le site portfolio', 'Realiser 3 projets vitrine', 'Configurer le formulaire de brief et Calendly', 'Lancer sur Twitter avec un thread avant/apres', 'Publier sur Indie Hackers', 'Atteindre 5K€ MRR en 60 jours'],
        contentAngles: ['Pourquoi votre landing page tue votre taux de conversion', 'Le defi de la landing page en 48h', 'Comment j\'ai construit un service design a 10K€/mois'],
        offerDesign: { mainOffer: '997€ pour une landing page complete en 48h', upsell: '1497€ avec redaction incluse', retainer: '2997€/mois pour 4 pages' },
        assumptions: ['Les fondateurs preferent la rapidite a la perfection', 'Twitter est le meilleur canal pour atteindre les indie hackers', 'Le workflow base sur les templates permet la livraison en 48h'],
        markdown: null,
      },
    ])

    // Creation de 3 validations business
    await BusinessValidation.createMany([
      {
        userId: member.id,
        inputTitle: 'Generateur de recettes IA pour le meal prep',
        inputDescription: 'Une appli qui genere des recettes hebdomadaires de meal prep personnalisees selon les preferences alimentaires, le budget et l\'equipement de cuisine disponible. Utilise l\'IA pour adapter les recettes et creer des listes de courses.',
        targetAudience: 'Millennials soucieux de leur sante qui veulent faire du meal prep mais manquent d\'inspiration',
        inputContext: { monetizationModel: 'freemium', distributionChannels: 'reseaux sociaux, blogs food', differentiation: 'Personnalisation IA + conscience du budget', technicalFeasibility: 'moderee', timeToMarket: '2-3 mois' },
        scoreGlobal: 71,
        scoreProblem: 16,
        scoreAudience: 12,
        scoreMonetization: 11,
        scoreDistribution: 10,
        scoreFeasibility: 12,
        scoreDifferentiation: 10,
        strengths: ['Probleme clair et parlant', 'Grand marche adressable', 'L\'IA apporte une vraie valeur a la personnalisation'],
        risks: ['Marche des applis de recettes tres concurrentiel', 'Defi de retention pour les applis de planification de repas', 'Risque d\'hallucination de l\'IA avec les donnees nutritionnelles'],
        recommendations: ['Commencer par une niche alimentaire specifique (ex. meal prep keto)', 'Construire une approche contenu-first sur TikTok/Instagram', 'Valider avec un MVP simple avant de construire le pipeline IA complet'],
        validationPlan: [{ day: 1, action: 'Creer une landing page avec la proposition de valeur', metric: 'Inscriptions email' }, { day: 3, action: 'Publier 5 exemples de plans repas sur Reddit r/mealprep', metric: 'Engagement et messages prives' }, { day: 5, action: 'Interviewer 10 utilisateurs potentiels sur leurs galeres de meal prep', metric: 'Validation des points de douleur' }, { day: 7, action: 'Lancer une version simple avec 20 recettes selectionnees', metric: 'Retention utilisateurs apres 1 semaine' }],
      },
      {
        userId: member.id,
        inputTitle: 'SaaS B2B de gestion de contrats freelances',
        inputDescription: 'Une plateforme qui aide les entreprises a gerer leurs relations freelances : contrats, paiements, conformite et suivi de performance en un seul endroit.',
        targetAudience: 'Startups et PME travaillant regulierement avec 10+ freelances',
        inputContext: { monetizationModel: 'abonnement', distributionChannels: 'linkedin, partenariats avec plateformes freelance', differentiation: 'Automatisation de la conformite + paiements integres', technicalFeasibility: 'complexe', timeToMarket: '4-6 mois' },
        scoreGlobal: 79,
        scoreProblem: 18,
        scoreAudience: 13,
        scoreMonetization: 14,
        scoreDistribution: 11,
        scoreFeasibility: 9,
        scoreDifferentiation: 14,
        strengths: ['Point de douleur B2B fort', 'Voie de monetisation claire', 'L\'economie freelance en croissance cree un vent favorable'],
        risks: ['Cycle de vente long en B2B', 'Exigences de conformite complexes selon les juridictions', 'Concurrence avec les plateformes RH etablies ajoutant des fonctionnalites freelance'],
        recommendations: ['Se concentrer sur une seule juridiction d\'abord', 'S\'associer avec des plateformes freelance pour la distribution', 'Commencer par la gestion de contrats avant d\'ajouter les paiements'],
        validationPlan: [{ day: 1, action: 'Interviewer 5 responsables ops de startups sur la gestion des freelances', metric: 'Score de severite du probleme' }, { day: 3, action: 'Creer un prototype cliquable du workflow principal', metric: 'Retours utilisateurs sur le workflow' }, { day: 5, action: 'Tester la sensibilite au prix avec un test A/B sur landing page', metric: 'Taux de conversion inscription' }, { day: 7, action: 'Obtenir 3 engagements pilotes d\'entreprises cibles', metric: 'Lettre d\'intention signee' }],
      },
      {
        userId: member.id,
        inputTitle: 'Marketplace de mode durable',
        inputDescription: 'Une marketplace connectant les consommateurs eco-responsables avec des marques de mode durable verifiees. Inclut un scoring de durabilite, une verification des marques et un suivi de l\'empreinte carbone.',
        targetAudience: 'Consommateurs eco-responsables de 22 a 35 ans',
        inputContext: { monetizationModel: 'commission', distributionChannels: 'instagram, blogs durabilite', differentiation: 'Systeme de verification de durabilite', technicalFeasibility: 'moderee', timeToMarket: '3-4 mois' },
        scoreGlobal: 58,
        scoreProblem: 12,
        scoreAudience: 10,
        scoreMonetization: 9,
        scoreDistribution: 8,
        scoreFeasibility: 10,
        scoreDifferentiation: 9,
        strengths: ['Demande croissante des consommateurs pour la durabilite', 'Motivation d\'achat emotionnelle', 'Potentiel de partenariats avec les marques'],
        risks: ['Probleme du demarrage a froid des marketplaces', 'La verification de durabilite est complexe et couteuse', 'Concurrence avec les marketplaces de mode etablies ajoutant des fonctionnalites durabilite', 'Faibles marges sur le modele commission'],
        recommendations: ['Commencer comme un annuaire curate avant de construire la marketplace complete', 'Se concentrer sur une seule categorie (ex. vetements de sport durables)', 'Envisager un modele affilie avant la commission pour reduire la complexite'],
        validationPlan: [{ day: 1, action: 'Curate une liste de 50 marques durables', metric: 'Taux de reponse des marques contactees' }, { day: 3, action: 'Construire une presence Instagram avec du contenu mode durable', metric: 'Croissance des abonnes et engagement' }, { day: 5, action: 'Lancer un annuaire simple avec des liens affilie', metric: 'Taux de clic et commissions' }, { day: 7, action: 'Sonder 50 consommateurs eco-responsables sur leurs habitudes d\'achat', metric: 'Volonte d\'utiliser une plateforme dediee' }],
      },
    ])
  }
}
